name: Temporary format source

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  format:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install clang-format
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install --quiet obsproject/tools/clang-format@19
      - name: Format source
        run: |
          clang-format-19 -style=file -fallback-style=none -i src/scrcpy-source.c
          if git diff --quiet -- src/scrcpy-source.c; then
            echo "Already formatted"
            exit 0
          fi
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add src/scrcpy-source.c
          git commit -m "Format scrcpy source"
          git push
